@echo off
cls
REM  make32.bat -  Batch file for assembling/linking 32-bit Assembly programs

REM  Revision history: 
REM  2/17/02: added the -Sg command line option (displays generated code generated by MASM)

REM The following three lines can be customized for your system:
REM ********************************************BEGIN customize
SET PATH=C:\Masm615
SET INCLUDE=C:\Masm615\INCLUDE
SET LIB=C:\Masm615\LIB
REM ********************************************END customize

ML /nologo -Zi -c -Fl -Sg -coff %1.asm
if errorlevel 1 goto terminate

REM add the /MAP option for a map file in the link command.

LINK32 /nologo %1.obj irvine32.lib kernel32.lib /SUBSYSTEM:CONSOLE /DEBUG /MAP
if errorLevel 1 goto terminate

dir %1.*

:terminate
pause